<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Wine Quiz — 25 Questions</title>
  <style>
    :root { --max: 900px; }
    body { font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
           line-height: 1.6; margin: 0; padding: 0; }
    header { background: #111; color: #fff; padding: 1.5rem 1rem; }
    header h1 { margin: 0; font-size: 1.6rem; }
    main { max-width: var(--max); margin: 1.5rem auto; padding: 0 1rem; }
    h2 { margin-top: 2rem; }
    ol { padding-left: 1.2rem; }
    li { margin: .8rem 0; }
    .card { background:#f8f8f8; border:1px solid #e5e5e5; border-radius: 10px; padding: 1rem; }
    footer { max-width: var(--max); margin: 2rem auto; padding: 0 1rem 2rem; color:#666; font-size:.9rem; }
  </style>
</head>
<body>
  <header>
    <h1>Wine Quiz — 25 Questions</h1>
  </header>

  <main>
    <div class="card">
      <p>Use this as a quick test in class. Multiple-choice answers are inline; short answers can be written in the blanks.</p>
    </div>

    <h2>General & Grapes</h2>
    <ol>
      <li>What is wine?<br>
        A) Fermented grape juice &nbsp; B) Fermented apple juice &nbsp; C) Fermented sugar water
      </li>

      <li>Which part of the grape contains the highest concentration of tannins?<br>
        A) Seeds and stems &nbsp; B) Pulp &nbsp; C) Skins
      </li>

      <li>Which part of the grape contains water and sugar?<br>
        A) Pulp &nbsp; B) Seeds &nbsp; C) Skins
      </li>

      <li>Skins of the grape provide:<br>
        A) Color, tannin, flavor &nbsp; B) Water and sugar &nbsp; C) Acidity only
      </li>

      <li>Between which latitudes do wine grapes grow best?<br>
        A) 10°–30° &nbsp; B) 30°–50° &nbsp; C) 50°–70°
      </li>
    </ol>

    <h2>Winemaking Styles</h2>
    <ol start="6">
      <li>Red wines are made by fermenting juice with:<br>
        A) Skins and stems &nbsp; B) Only pulp &nbsp; C) Only seeds
      </li>

      <li>White wines are usually made by fermenting juice without:<br>
        A) Skins, stems, and pips &nbsp; B) Alcohol &nbsp; C) Yeast
      </li>

      <li>Rosé wine is made by:<br>
        A) Fermenting juice with skins until fully red &nbsp; B) Short skin contact then juice is drained &nbsp; C) Blending white grapes with red grapes
      </li>

      <li>Sparkling wine made in Champagne uses:<br>
        A) CO₂ injection &nbsp; B) Tank fermentation &nbsp; C) Bottle fermentation
      </li>

      <li>Which sparkling style uses tank fermentation?<br>
        A) Champagne &nbsp; B) Prosecco &nbsp; C) Cava
      </li>
    </ol>

    <h2>Traits of Wine</h2>
    <ol start="11">
      <li>Which wine trait makes your mouth feel “fuzzy” or like your teeth wear socks?<br>
        A) Tannin &nbsp; B) Acidity &nbsp; C) Alcohol
      </li>

      <li>Which trait gives wine freshness and “snap”?<br>
        A) Tannin &nbsp; B) Acidity &nbsp; C) Residual sugar
      </li>

      <li>What is residual sugar (RS)?<br>
        <em>(short answer)</em>
      </li>

      <li>Alcohol contributes mainly to:<br>
        A) Color &nbsp; B) Body &nbsp; C) Acidity
      </li>

      <li>Match the alcohol levels:<br>
        Below 11% = ________ &nbsp; 11–13.9% = ________ &nbsp; 14% and above = ________
      </li>
    </ol>

    <h2>Sweetness & Special Wines</h2>
    <ol start="16">
      <li>Dry wines make up roughly how much of global consumption?<br>
        A) Half &nbsp; B) Two-thirds &nbsp; C) Almost all
      </li>

      <li>Which is a fortified wine?<br>
        A) Port &nbsp; B) Sancerre &nbsp; C) Prosecco
      </li>

      <li>How is fermentation stopped in fortified wines like Port?<br>
        <em>(short answer)</em>
      </li>

      <li>What is Botrytis (Noble Rot) and what does it do to grapes?<br>
        <em>(short answer)</em>
      </li>

      <li>Grapes for Ice Wine are harvested when:<br>
        A) Overripe &nbsp; B) Frozen &nbsp; C) Dried on mats
      </li>
    </ol>

    <h2>Grape Varieties & Styles</h2>
    <ol start="21">
      <li>In cool climates, Chardonnay typically tastes of:<br>
        A) Apple and lemon &nbsp; B) Peach and pineapple &nbsp; C) Mango and banana
      </li>

      <li>Sauvignon Blanc is usually:<br>
        A) Sweet, low acid &nbsp; B) Dry, high acid, herbaceous &nbsp; C) Full-bodied, high tannin
      </li>

      <li>Pinot Noir is:<br>
        A) Dry, high acidity, red fruit flavors &nbsp; B) Sweet, tropical, medium acid &nbsp; C) High tannin, black fruit, spicy
      </li>

      <li>Which grape is often blended with Merlot in Bordeaux for structure and tannins?<br>
        A) Cabernet Sauvignon &nbsp; B) Pinot Gris &nbsp; C) Riesling
      </li>

      <li>Shiraz (Australia) compared to Syrah (France) tends to be:<br>
        A) Lighter, with green apple notes &nbsp; B) Fuller-bodied, jammy black fruit &nbsp; C) Always sparkling
      </li>
    </ol>
  </main>

  <footer>
    <p>Ready for GitHub Pages. Drop this file in <code>docs/</code> and commit to <code>main</code>.</p>
  </footer>
</body>
</html>
